/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package activity;

import java.sql.Connection;
import java.sql.ResultSet;
import database.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Vinayak
 */
public class history extends javax.swing.JFrame {
    Connection con = connect.setConnection();
    process pr = new process();
    DefaultTableModel dtm;
    /**
     * Creates new form history
     */
    public history() {
        initComponents();
        int slt;
       Long pho;
       String name, veh,timein,timeout,type;
       Float charge;
       try{
            ResultSet rs;
            dtm = (DefaultTableModel) hist.getModel();
            dtm.setRowCount(0);
            rs = pr.his(con);
            while(rs.next()){
                veh = rs.getString("vehicleNo");
                name = rs.getString("name");
                pho = rs.getLong("phone");
                slt = rs.getInt("slot");
                type = rs.getString("type");
                timein = rs.getString("timein");
                timeout = rs.getString("timeout");
                charge= rs.getFloat("charge");
                dtm.addRow(new Object[]{veh,name,pho,slt,type,timein,timeout,charge});
            }
            System.out.println("Done All good");
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null,e.getMessage(),"Error!", JOptionPane.ERROR_MESSAGE);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hist = new javax.swing.JTable();
        close = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        filter = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        value = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Welcome to History Page");

        hist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle No.", "Name", "Phone", "Slot", "Type", "Time In", "Time Out", "Charge"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        hist.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(hist);
        if (hist.getColumnModel().getColumnCount() > 0) {
            hist.getColumnModel().getColumn(0).setMaxWidth(100);
            hist.getColumnModel().getColumn(1).setPreferredWidth(130);
            hist.getColumnModel().getColumn(1).setMaxWidth(120);
            hist.getColumnModel().getColumn(2).setMaxWidth(180);
            hist.getColumnModel().getColumn(3).setMaxWidth(50);
            hist.getColumnModel().getColumn(4).setMaxWidth(100);
            hist.getColumnModel().getColumn(7).setMaxWidth(100);
        }

        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jLabel2.setText("Filters: ");

        filter.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Slot", "Vehicle No.", "Phone", "Two Wheeler", "Four Wheeler" }));

        jButton1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(close))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(booking.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            dispose();
        }
    }//GEN-LAST:event_closeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int t = filter.getSelectedIndex();
        ResultSet rs;
        String val = value.getText();
        String match,fil = null;
        switch (t) {
            case 1:
                match = "slot";
                fil = val;
                break;
            case 2:
                match = "vehicleNo";
                fil = val;
                break;
            case 3:
                match = "phone";
                fil = val;
                break;
            case 4:
                match = "TwoWheeler";
                break;
            case 5:
                match = "FourWheeler";
                break;
            default:
                match =null;
                break;
        }
        if (match == null){
            rs = pr.his(con);
        }
        else if(fil == null){
            rs = pr.his(con,match);
        }
        else{
            rs = pr.his(con,match,fil);
        }
        int slt;
        Long pho;
        String name, veh,timein,timeout,type;
        Float charge;
        dtm = (DefaultTableModel) hist.getModel();
        dtm.setRowCount(0);
        try {
            while(rs.next()){
                veh = rs.getString("veh"
                        + "icleNo");
                name = rs.getString("name");
                pho = rs.getLong("phone");
                slt = rs.getInt("slot");
                type = rs.getString("type");
                timein = rs.getString("timein");
                timeout = rs.getString("timeout");
                charge= rs.getFloat("charge");
                dtm.addRow(new Object[]{veh,name,pho,slt,type,timein,timeout,charge});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"No Data Found","Error!", JOptionPane.ERROR_MESSAGE);
        }
            System.out.println("Done All good");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new history().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JComboBox<String> filter;
    private javax.swing.JTable hist;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField value;
    // End of variables declaration//GEN-END:variables
}
